### PR TITLE
Negative parameter initialization.

### PR DESCRIPTION
**Pull request by riaanvddool**
I am still trying to figure out how best to submit changes given that i dont have write access to the repo

R.

### CODE REVIEW

**Comment by stefanv** [comment]
Usually, you would create a branch in your repository, make the changes, and then file a pull request, at which time the main repository owner would merge your changes.  But seems your write access is working now!

**Comment by riaanvddool** [comment]
From http://help.github.com/send-pull-requests/:

"The Shared Repository Model is more prevalent with small teams and organizations collaborating on private projects. Everyone is granted push access to a single shared repository and topic branches are used to isolate changes."

I think the project is probably small enough to follow this model.

**Comment by stefanv** [comment]
It varies a lot from project to project; in some sense, a small project is even easier to run in a distributed fashion.  But in our case it really doesn't matter all that much!

**Comment by nfaggian** [comment]
Happy for us to use feature branches on a shared repository and just be sensible with commits - if we get decent tests we should run them all before each commit.

**Pull request merged**
